[bindings.kotlin]
package_name = "to.iris.chat.rust"
cdylib_name = "iris_chat_core"

[bindings.swift]
module_name = "IrisChatCore"

[bindings.csharp]
namespace = "IrisChat.Bindings"
access_modifier = "public"
global_methods_class_name = "Native"
