[bindings.kotlin]
package_name = "social.innode.ndr.demo.rust"
cdylib_name = "ndr_demo_core"

[bindings.swift]
module_name = "NdrDemoCore"

[bindings.csharp]
namespace = "IrisChat.Bindings"
access_modifier = "public"
global_methods_class_name = "Native"
