#!/usr/bin/env python3
"""Regenerate iOS and macOS app icons from a clean transparent source.

Source: iris-chat-flutter/assets/icons/iris_logo.png (512x512 RGBA, clean alpha).
The previous icons were generated by compositing a pre-baked variant where
anti-aliased edges had been flattened against a non-matching background,
leaving purple fringing around the logo edges.
"""
import os
import sys
from pathlib import Path
from PIL import Image

REPO = Path(__file__).resolve().parent.parent
SRC = Path(os.environ.get(
    "IRIS_LOGO_SRC",
    Path.home() / "src/iris-chat-flutter/assets/icons/iris_logo.png",
))
BG = (0, 0, 0)  # solid black

IOS_DIR = REPO / "ios/Assets.xcassets/AppIcon.appiconset"
MAC_DIR = REPO / "macos/Assets.xcassets/AppIcon.appiconset"

IOS_OUTPUTS = {
    "Icon-App-20x20@1x.png": 20,
    "Icon-App-20x20@2x.png": 40,
    "Icon-App-20x20@3x.png": 60,
    "Icon-App-29x29@1x.png": 29,
    "Icon-App-29x29@2x.png": 58,
    "Icon-App-29x29@3x.png": 87,
    "Icon-App-40x40@1x.png": 40,
    "Icon-App-40x40@2x.png": 80,
    "Icon-App-40x40@3x.png": 120,
    "Icon-App-50x50@1x.png": 50,
    "Icon-App-50x50@2x.png": 100,
    "Icon-App-57x57@1x.png": 57,
    "Icon-App-57x57@2x.png": 114,
    "Icon-App-60x60@2x.png": 120,
    "Icon-App-60x60@3x.png": 180,
    "Icon-App-72x72@1x.png": 72,
    "Icon-App-72x72@2x.png": 144,
    "Icon-App-76x76@1x.png": 76,
    "Icon-App-76x76@2x.png": 152,
    "Icon-App-83.5x83.5@2x.png": 167,
    "Icon-App-1024x1024@1x.png": 1024,
}

MAC_OUTPUTS = {
    "app_icon_16.png": 16,
    "app_icon_32.png": 32,
    "app_icon_64.png": 64,
    "app_icon_128.png": 128,
    "app_icon_256.png": 256,
    "app_icon_512.png": 512,
    "app_icon_1024.png": 1024,
}


def build_master(size: int) -> Image.Image:
    """Composite the transparent logo onto a solid background at the given size."""
    src = Image.open(SRC).convert("RGBA")
    if src.size != (size, size):
        src = src.resize((size, size), Image.LANCZOS)
    bg = Image.new("RGB", (size, size), BG)
    bg.paste(src, (0, 0), src)
    return bg


def write_outputs(out_dir: Path, outputs: dict[str, int]) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    # Build a high-res master once, then downscale for each target. Per-target
    # composites would also work but produce identical pixels since alpha is
    # blended before resizing in both cases.
    master = build_master(1024)
    for filename, size in outputs.items():
        if size == 1024:
            img = master
        else:
            img = master.resize((size, size), Image.LANCZOS)
        path = out_dir / filename
        img.save(path, "PNG", optimize=True)
        print(f"  {path.relative_to(REPO)} ({size}x{size})")


def write_icns() -> None:
    """Build a macOS .icns bundle alongside the appiconset PNGs."""
    import subprocess
    import tempfile

    iconset_dir = MAC_DIR / "_tmp.iconset"
    if iconset_dir.exists():
        for p in iconset_dir.iterdir():
            p.unlink()
        iconset_dir.rmdir()
    iconset_dir.mkdir()

    pairs = [
        (16, "icon_16x16.png"),
        (32, "icon_16x16@2x.png"),
        (32, "icon_32x32.png"),
        (64, "icon_32x32@2x.png"),
        (128, "icon_128x128.png"),
        (256, "icon_128x128@2x.png"),
        (256, "icon_256x256.png"),
        (512, "icon_256x256@2x.png"),
        (512, "icon_512x512.png"),
        (1024, "icon_512x512@2x.png"),
    ]
    master = build_master(1024)
    for size, name in pairs:
        img = master if size == 1024 else master.resize((size, size), Image.LANCZOS)
        img.save(iconset_dir / name, "PNG", optimize=True)

    out = MAC_DIR / "app_icon.icns"
    subprocess.run(
        ["iconutil", "-c", "icns", "-o", str(out), str(iconset_dir)],
        check=True,
    )
    for p in iconset_dir.iterdir():
        p.unlink()
    iconset_dir.rmdir()
    print(f"  {out.relative_to(REPO)}")


def main() -> None:
    if not SRC.exists():
        print(f"source not found: {SRC}", file=sys.stderr)
        sys.exit(1)
    print(f"source: {SRC}")
    print("iOS:")
    write_outputs(IOS_DIR, IOS_OUTPUTS)
    print("macOS:")
    write_outputs(MAC_DIR, MAC_OUTPUTS)
    write_icns()


if __name__ == "__main__":
    main()
